spring:
  application:
    name: elearning-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: ElearningHikariPool
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

springdoc:
  paths-to-match: /lms/**
