spring:
  application:
    name: elearning-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20

springdoc:
  paths-to-match: /lms/**

